### ISSUE TITLE
Evaluating on DST

### ISSUE THREAD

**Issue by daisyworker** [TonyNemo/UBAR-MultiWOZ#1]
Hi, 

When evaluating on DST, it seems that the parameter "max_context_length"  is in need but not specified in any config files. Could you please verify the value for the parameter when solely evaluating on DST?

Another tiny concern is the DST evaluation command, is it "use_true_pv_resp" or "use_true_prev_resp"?

Many thanks

**Comment by TonyNemo** [comment]
Hi,
The "max_context_length" is 900. We have updated the config files.

It is "use_true_prev_resp".

**Comment by libing125** [comment]
It seems the checkpoint you release is not identical with the DST-UBAR mentioned in the paper. Can you release DST-UBAR checkpoint or the joint acc in your paper can be achieved using the checkpoint `all_0729_sd11_lr0.0001_bs2_ga16`?
Thanks
